{
 "title": "juno",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "juno" },
   { "name": "group", "label": "Group", "query": "daq" }
  ]
 },
 "panels": [
  {
   "title": "home",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.da:da-.*.input_ros_volume.rate\"} >= 0)/1000/1000/1000",
     "legendFormat": "DA_Input"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_WAVEFORM.input_data.rate\"}  >= 0)/1000/1000/1000",
     "legendFormat": "ROS_CD_WF"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_TQ.input_data.rate\"}  >= 0)/1000/1000/1000",
     "legendFormat": "ROS_CD_TQ"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_SPMT.input_data.rate\"}  >= 0)/1000/1000/1000",
     "legendFormat": "ROS_CD_SPMT"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.WP_WAVEFORM.input_data.rate\"}  >= 0)/1000/1000/1000",
     "legendFormat": "ROS_WP_WF"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.WP_TQ.input_data.rate\"}  >= 0)/1000/1000/1000",
     "legendFormat": "ROS_WP_TQ"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-mpmt.*.input_data.rate\"}  >= 0)/1000/1000/1000",
     "legendFormat": "ROS_WP_MPMT"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-tt.*.input_data.rate\"}  >= 0)/1000/1000/1000",
     "legendFormat": "ROS_TT"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-rpc.*.input_data.rate\"}  >= 0)/1000/1000/1000",
     "legendFormat": "ROS_RPC"
    }
   ]
  },
  {
   "title": "Storage data rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.es:ds-.*.saved_event_volume.rate\"} >= 0)/1000000",
     "legendFormat": "Total data rate"
    },
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.es:ds-2.saved_event_volume.rate\"}/1000000 >= 0",
     "legendFormat": "Global data rate"
    },
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.es:ds-3.saved_event_volume.rate\"}/1000000 >= 0",
     "legendFormat": "MM data rate"
    },
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.es:ds-4.saved_event_volume.rate\"}/1000000 >= 0",
     "legendFormat": "Software trigger data rate"
    },
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.es:ds-5.saved_event_volume.rate\"}/1000000 >= 0",
     "legendFormat": "LowE data rate"
    },
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.es:ds-6.saved_event_volume.rate\"}/1000000 >= 0",
     "legendFormat": "TT data rate"
    },
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.es:ds-7.saved_event_volume.rate\"}/1000000 >= 0",
     "legendFormat": "MPMT data rate"
    },
    {
     "expr": "sum(avg_over_time(oec{label=~\"${namespace}_${group}.df.es:ds-.*.saved_event_volume.rate\"}[30s])/1000000 >= 0)",
     "legendFormat": "Avg_total rate in 30s"
    },
    {
     "expr": "sum(avg_over_time(oec{label=~\"${namespace}_${group}.df.es:ds-2.saved_event_volume.rate\"}[10s])/1000000 >= 0)",
     "legendFormat": "Avg_global rate in 10s"
    }
   ]
  },
  {
   "title": "Assembly rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "oec{label=\"CD_event_channel_num_assembly_rate\"}*100",
     "legendFormat": "CD_event_channel_num_assembly_rate"
    },
    {
     "expr": "oec{label=\"CD_event_channel_num_accumulate_assembly_rate\"}*100",
     "legendFormat": "CD_event_channel_num_accumulate_assembly_rate"
    },
    {
     "expr": "oec{label=\"WP_event_channel_num_assembly_rate\"}*100",
     "legendFormat": "WP_event_channel_num_assembly_rate"
    },
    {
     "expr": "oec{label=\"WP_event_channel_num_accumulate_assembly_rate\"}*100",
     "legendFormat": "WP_event_channel_num_accumulate_assembly_rate"
    }
   ]
  },
  {
   "title": "CTU trigger rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "oec{label=~\"Rate_cd.ctu\"}",
     "legendFormat": "CD rate"
    },
    {
     "expr": "oec{label=~\"Rate_veto.ctu\"}",
     "legendFormat": "VETO rate"
    },
    {
     "expr": "oec{label=~\"Rate_cd.ctu\"} == 0 or oec{label=~\"Rate_cd.ctu\"} > 5000",
     "legendFormat": "CD-ABNORMAL"
    },
    {
     "expr": "oec{label=~\"Rate_veto_raw.ctu\"}",
     "legendFormat": "RAW VETO rate"
    },
    {
     "expr": "oec{label=~\"Rate_cd_raw.ctu\"}",
     "legendFormat": "RAW CD rate"
    }
   ]
  },
  {
   "title": "Data flow latency(s) vs host time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.processor:dp-.*.dp_time_bias\"} >= 0)/count(oec{label=~\"${namespace}_${group}.df.processor:dp-.*.dp_time_bias\"} >=0) / 1000",
     "legendFormat": "dp latency"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.da:da-.*.da_time_bias\"} >= 0)/count(oec{label=~\"${namespace}_${group}.df.da:da-.*.da_time_bias\"} >=0 ) / 1000",
     "legendFormat": "da latency"
    },
    {
     "expr": "sum(oec{label=\"${namespace}_${group}.df.es:ds-2.delta_time\"} < 999999)",
     "legendFormat": "ds latency"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.da:da-.*.ros_time_bias\"} >=0)/count(oec{label=~\"${namespace}_${group}.df.da:da-.*.ros_time_bias\"} >=0) / 1000",
     "legendFormat": "ros ready latency"
    }
   ]
  },
  { "title": "ROS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "ROS Drop Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_WAVEFORM.drop_count\"} >= 0)\r\n  - \r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_WAVEFORM.drop_count\"} offset 1m >= 0),\r\n  0\r\n)",
     "legendFormat": "CD_WF last 1 min"
    },
    {
     "expr": "clamp_min(\r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_TQ.drop_count\"} >= 0)\r\n  - \r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_TQ.drop_count\"} offset 1m >= 0),\r\n  0\r\n)",
     "legendFormat": "CD_TQ last 1min"
    },
    {
     "expr": "clamp_min(\r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.WP_WAVEFORM.drop_count\"} >= 0)\r\n  - \r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.WP_WAVEFORM.drop_count\"} offset 1m >= 0),\r\n  0\r\n)",
     "legendFormat": "WP_WF last 1 min"
    },
    {
     "expr": "clamp_min(\r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.WP_TQ.drop_count\"} >= 0)\r\n  - \r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.WP_TQ.drop_count\"} offset 1m >= 0),\r\n  0\r\n)",
     "legendFormat": "WP_TQ last 1 min"
    },
    {
     "expr": "clamp_min(\r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_SPMT.drop_count\"} >= 0)\r\n  - \r\n  sum(oec{label=~\"${namespace}_${group}.ex.df.ro-.*.CD_SPMT.drop_count\"} offset 1m >= 0),\r\n  0\r\n)",
     "legendFormat": "CD_SPMT last 1 min"
    }
   ]
  },
  {
   "title": "TFM time fragment rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(oec{label=\"${namespace}_${group}.ex.df.tfm-0:l1id_count.rate\"})",
     "legendFormat": "TFM time fragment rate"
    }
   ]
  },
  { "title": "Trigger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "BEC Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "oec{label=~\"Rate_hit.bec.*\"} >= 0"
    }
   ]
  },
  {
   "title": "BEC Rate Recv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oec{label=~\"Rate_recv.bec.*\"} >= 0"
    }
   ]
  },
  {
   "title": "BEC Rate Send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "oec{label=~\"Rate_send.bec.*\"} >= 0"
    }
   ]
  },
  {
   "title": "MM Readout Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.ex.df.ro-mm-0:FEE_10002.MM.input_data.rate\"})/32",
     "legendFormat": "MM event rate"
    }
   ]
  },
  { "title": "Data Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "DA fragment number",
   "type": "timeseries",
   "description": "ROS-DA-DP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.da:da-.*.[.]fragment_counter\"}"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.da:da-.*.[.]fragment_counter\"})",
     "legendFormat": "Sum of DA fragments"
    }
   ]
  },
  {
   "title": "DP fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.processor.*.fragment_counter\"} >= 0"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.processor.*.fragment_counter\"} >= 0 )"
    }
   ]
  },
  {
   "title": "DP detail processing time(ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.HEC_time\"}>=0)/count(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.HEC_time\"}>=0)",
     "legendFormat": "HEC time"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.process_time_without_hec\"} >= 0)/count(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.process_time_without_hec\"}>=0)",
     "legendFormat": "data process + data storage time"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.LEC_time\"}>=0)/count(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.LEC_time\"}>=0)",
     "legendFormat": "LEC time"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.CCSN_time\"}>=0)/count(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.CCSN_time\"}>=0)",
     "legendFormat": "CCSN time"
    }
   ]
  },
  {
   "title": "DS order dict size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.es:ds-.*.order_dict_size\"} >= 0"
    }
   ]
  },
  {
   "title": "DS input buffer size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "oec{label=~\"${namespace}_${group}.df.es:ds-.*.input_buffer_size\"} >= 0"
    }
   ]
  },
  {
   "title": "oec storage status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.save_full_waveform.total\"}>=0)",
     "legendFormat": "full_channel"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.save_fired_waveform.total\"}>=0)",
     "legendFormat": "fired_channel"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.save_partial_fired_waveform.total\"}>=0)",
     "legendFormat": "partial_fired_ch"
    },
    {
     "expr": "sum(oec{label=~\"${namespace}_${group}.df.DP.dp-.*.save_only_tq.total\"}>=0)",
     "legendFormat": "save_only_tq"
    }
   ]
  },
  { "title": "8inch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "8inchPMT-triggerRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "oec{label=~\"top-PMT-dcr.VME1.triggerRate\"} ",
     "legendFormat": "VME1"
    },
    {
     "expr": "oec{label=~\"top-PMT-dcr.VME2.triggerRate\"} ",
     "legendFormat": "VME2"
    },
    {
     "expr": "oec{label=~\"top-PMT-dcr.VME3.triggerRate\"} ",
     "legendFormat": "VME3"
    },
    {
     "expr": "oec{label=~\"top-PMT-dcr.VME4.triggerRate\"} ",
     "legendFormat": "VME4"
    }
   ]
  }
 ]
}